name: persisted_objects
description: Helper package to store/retrieve
version: 0.0.2+0
author: StevenSmith@ICodeForYou.com
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^1.0.14
  flutter_secure_storage: ^3.3.5
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
